#[allow(non_camel_case_types)]

// From https://en.bitcoin.it/wiki/Script
// and https://github.com/bitcoin/bitcoin/blob/master/src/script/script.h
#[derive(Debug)]
pub enum OPCode {
    Data(Vec<u8>),

    OP_0,
    OP_PUSHDATA1,
    OP_PUSHDATA2,
    OP_PUSHDATA4,
    OP_1NEGATE,
    OP_RESERVED,
    OP_1,
    OP_2,
    OP_3,
    OP_4,
    OP_5,
    OP_6,
    OP_7,
    OP_8,
    OP_9,
    OP_10,
    OP_11,
    OP_12,
    OP_13,
    OP_14,
    OP_15,
    OP_16,
    OP_NOP,
    OP_VER,
    OP_IF,
    OP_NOTIF,
    OP_VERIF,
    OP_VERNOTIF,
    OP_ELSE,
    OP_ENDIF,
    OP_VERIFY,
    OP_RETURN,
    OP_TOALTSTACK,
    OP_FROMALTSTACK,
    OP_2DROP,
    OP_2DUP,
    OP_3DUP,
    OP_2OVER,
    OP_2ROT,
    OP_2SWAP,
    OP_IFDUP,
    OP_DEPTH,
    OP_DROP,
    OP_DUP,
    OP_NIP,
    OP_OVER,
    OP_PICK,
    OP_ROLL,
    OP_ROT,
    OP_SWAP,
    OP_TUCK,
    OP_CAT,
    OP_SUBSTR,
    OP_LEFT,
    OP_RIGHT,
    OP_SIZE,
    OP_INVERT,
    OP_AND,
    OP_OR,
    OP_XOR,
    OP_EQUAL,
    OP_EQUALVERIFY,
    OP_RESERVED1,
    OP_RESERVED2,
    OP_1ADD,
    OP_1SUB,
    OP_2MUL,
    OP_2DIV,
    OP_NEGATE,
    OP_ABS,
    OP_NOT,
    OP_0NOTEQUAL,
    OP_ADD,
    OP_SUB,
    OP_MUL,
    OP_DIV,
    OP_MOD,
    OP_LSHIFT,
    OP_RSHIFT,
    OP_BOOLAND,
    OP_BOOLOR,
    OP_NUMEQUAL,
    OP_NUMEQUALVERIFY,
    OP_NUMNOTEQUAL,
    OP_LESSTHAN,
    OP_GREATERTHAN,
    OP_LESSTHANOREQUAL,
    OP_GREATERTHANOREQUAL,
    OP_MIN,
    OP_MAX,
    OP_WITHIN,
    OP_RIPEMD160,
    OP_SHA1,
    OP_SHA256,
    OP_HASH160,
    OP_HASH256,
    OP_CODESEPARATOR,
    OP_CHECKSIG,
    OP_CHECKSIGVERIFY,
    OP_CHECKMULTISIG,
    OP_CHECKMULTISIGVERIFY,
    OP_NOP1,
    OP_CHECKLOCKTIMEVERIFY,
    OP_CHECKSEQUENCEVERIFY,
    OP_NOP4,
    OP_NOP5,
    OP_NOP6,
    OP_NOP7,
    OP_NOP8,
    OP_NOP9,
    OP_NOP10,
    OP_CHECKSIGADD,
    OP_INVALIDOPCODE,

    Unknown,
}

pub fn byte_to_opcode(byte: u8) -> OPCode {
    match byte {
        0x00 => OPCode::OP_0,
        0x4c => OPCode::OP_PUSHDATA1,
        0x4d => OPCode::OP_PUSHDATA2,
        0x4e => OPCode::OP_PUSHDATA4,
        0x4f => OPCode::OP_1NEGATE,
        0x50 => OPCode::OP_RESERVED,
        0x51 => OPCode::OP_1,
        0x52 => OPCode::OP_2,
        0x53 => OPCode::OP_3,
        0x54 => OPCode::OP_4,
        0x55 => OPCode::OP_5,
        0x56 => OPCode::OP_6,
        0x57 => OPCode::OP_7,
        0x58 => OPCode::OP_8,
        0x59 => OPCode::OP_9,
        0x5a => OPCode::OP_10,
        0x5b => OPCode::OP_11,
        0x5c => OPCode::OP_12,
        0x5d => OPCode::OP_13,
        0x5e => OPCode::OP_14,
        0x5f => OPCode::OP_15,
        0x60 => OPCode::OP_16,
        0x61 => OPCode::OP_NOP,
        0x62 => OPCode::OP_VER,
        0x63 => OPCode::OP_IF,
        0x64 => OPCode::OP_NOTIF,
        0x65 => OPCode::OP_VERIF,
        0x66 => OPCode::OP_VERNOTIF,
        0x67 => OPCode::OP_ELSE,
        0x68 => OPCode::OP_ENDIF,
        0x69 => OPCode::OP_VERIFY,
        0x6a => OPCode::OP_RETURN,
        0x6b => OPCode::OP_TOALTSTACK,
        0x6c => OPCode::OP_FROMALTSTACK,
        0x6d => OPCode::OP_2DROP,
        0x6e => OPCode::OP_2DUP,
        0x6f => OPCode::OP_3DUP,
        0x70 => OPCode::OP_2OVER,
        0x71 => OPCode::OP_2ROT,
        0x72 => OPCode::OP_2SWAP,
        0x73 => OPCode::OP_IFDUP,
        0x74 => OPCode::OP_DEPTH,
        0x75 => OPCode::OP_DROP,
        0x76 => OPCode::OP_DUP,
        0x77 => OPCode::OP_NIP,
        0x78 => OPCode::OP_OVER,
        0x79 => OPCode::OP_PICK,
        0x7a => OPCode::OP_ROLL,
        0x7b => OPCode::OP_ROT,
        0x7c => OPCode::OP_SWAP,
        0x7d => OPCode::OP_TUCK,
        0x7e => OPCode::OP_CAT,
        0x7f => OPCode::OP_SUBSTR,
        0x80 => OPCode::OP_LEFT,
        0x81 => OPCode::OP_RIGHT,
        0x82 => OPCode::OP_SIZE,
        0x83 => OPCode::OP_INVERT,
        0x84 => OPCode::OP_AND,
        0x85 => OPCode::OP_OR,
        0x86 => OPCode::OP_XOR,
        0x87 => OPCode::OP_EQUAL,
        0x88 => OPCode::OP_EQUALVERIFY,
        0x89 => OPCode::OP_RESERVED1,
        0x8a => OPCode::OP_RESERVED2,
        0x8b => OPCode::OP_1ADD,
        0x8c => OPCode::OP_1SUB,
        0x8d => OPCode::OP_2MUL,
        0x8e => OPCode::OP_2DIV,
        0x8f => OPCode::OP_NEGATE,
        0x90 => OPCode::OP_ABS,
        0x91 => OPCode::OP_NOT,
        0x92 => OPCode::OP_0NOTEQUAL,
        0x93 => OPCode::OP_ADD,
        0x94 => OPCode::OP_SUB,
        0x95 => OPCode::OP_MUL,
        0x96 => OPCode::OP_DIV,
        0x97 => OPCode::OP_MOD,
        0x98 => OPCode::OP_LSHIFT,
        0x99 => OPCode::OP_RSHIFT,
        0x9a => OPCode::OP_BOOLAND,
        0x9b => OPCode::OP_BOOLOR,
        0x9c => OPCode::OP_NUMEQUAL,
        0x9d => OPCode::OP_NUMEQUALVERIFY,
        0x9e => OPCode::OP_NUMNOTEQUAL,
        0x9f => OPCode::OP_LESSTHAN,
        0xa0 => OPCode::OP_GREATERTHAN,
        0xa1 => OPCode::OP_LESSTHANOREQUAL,
        0xa2 => OPCode::OP_GREATERTHANOREQUAL,
        0xa3 => OPCode::OP_MIN,
        0xa4 => OPCode::OP_MAX,
        0xa5 => OPCode::OP_WITHIN,
        0xa6 => OPCode::OP_RIPEMD160,
        0xa7 => OPCode::OP_SHA1,
        0xa8 => OPCode::OP_SHA256,
        0xa9 => OPCode::OP_HASH160,
        0xaa => OPCode::OP_HASH256,
        0xab => OPCode::OP_CODESEPARATOR,
        0xac => OPCode::OP_CHECKSIG,
        0xad => OPCode::OP_CHECKSIGVERIFY,
        0xae => OPCode::OP_CHECKMULTISIG,
        0xaf => OPCode::OP_CHECKMULTISIGVERIFY,
        0xb0 => OPCode::OP_NOP1,
        0xb1 => OPCode::OP_CHECKLOCKTIMEVERIFY,
        0xb2 => OPCode::OP_CHECKSEQUENCEVERIFY,
        0xb3 => OPCode::OP_NOP4,
        0xb4 => OPCode::OP_NOP5,
        0xb5 => OPCode::OP_NOP6,
        0xb6 => OPCode::OP_NOP7,
        0xb7 => OPCode::OP_NOP8,
        0xb8 => OPCode::OP_NOP9,
        0xb9 => OPCode::OP_NOP10,
        0xba => OPCode::OP_CHECKSIGADD,
        0xff => OPCode::OP_INVALIDOPCODE,

        _ => OPCode::Unknown,
    }
}
